###

POST http://localhost:3002/inventory
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJlZDE0MDUxLTBjY2EtNDc1MC1iOWVkLTk0Zjg2ODMwODQzZiIsInN1YiI6ImpvaG5kb2UxIiwiaWF0IjoxNzY2NTU1ODI3LCJleHAiOjE3NjY2NDIyMjd9.z0mY7-n_6f9Od7ytM2HgpXJO-g5kUzqOBrKb--xEZtc
Content-Type: application/json

{
    "availableQty": 100,
    "productId": "some-product-uuid"
}

###
POST http://localhost:3002/inventory/adjust-stock
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJlZDE0MDUxLTBjY2EtNDc1MC1iOWVkLTk0Zjg2ODMwODQzZiIsInN1YiI6ImpvaG5kb2UxIiwiaWF0IjoxNzY2NTU1ODI3LCJleHAiOjE3NjY2NDIyMjd9.z0mY7-n_6f9Od7ytM2HgpXJO-g5kUzqOBrKb--xEZtc
Content-Type: application/json

{
    "productId": "some-product-uuid",
    "quantity": 50
}

###
GET http://localhost:3002/inventory/some-product-uuid
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJlZDE0MDUxLTBjY2EtNDc1MC1iOWVkLTk0Zjg2ODMwODQzZiIsInN1YiI6ImpvaG5kb2UxIiwiaWF0IjoxNzY2NTU1ODI3LCJleHAiOjE3NjY2NDIyMjd9.z0mY7-n_6f9Od7ytM2HgpXJO-g5kUzqOBrKb--xEZtc