###
GET http://localhost:3000/order
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImRmNzNjMjllLTFiNzQtNGMyYi05NjMxLWY0NzhiMDQ3ZjhlNiIsIm5hbWUiOiJKb2huIERvZSIsImVtYWlsIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3NjgwOTg5ODUsImV4cCI6MTc2ODE4NTM4NX0.q1iZYWvgjocmFgIr6eItxLYF0M4pl76ptKc-SpbI7Mc



###
POST http://localhost:3000/order
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImRmNzNjMjllLTFiNzQtNGMyYi05NjMxLWY0NzhiMDQ3ZjhlNiIsIm5hbWUiOiJKb2huIERvZSIsImVtYWlsIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3NjgwOTg5ODUsImV4cCI6MTc2ODE4NTM4NX0.q1iZYWvgjocmFgIr6eItxLYF0M4pl76ptKc-SpbI7Mc

{
    "items": [
        {
            "productId": "446e250d-d579-4625-b032-e36fb4a1b166",
            "quantity": 200,
            "price": 19.99
        }
    ],
    "shippingAddress": {
        "address1": "123 Main St",
        "city": "Anytown",
        "state": "CA",
        "postalCode": "12345",
        "country": "USA"
    },
    "paymentId": "0f189ef0-5376-48aa-bdc9-7649ddc3ac44"      
}