

###
GET http://localhost:3000/category
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImRmNzNjMjllLTFiNzQtNGMyYi05NjMxLWY0NzhiMDQ3ZjhlNiIsIm5hbWUiOiJKb2huIERvZSIsImVtYWlsIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3NjgwOTg5ODUsImV4cCI6MTc2ODE4NTM4NX0.q1iZYWvgjocmFgIr6eItxLYF0M4pl76ptKc-SpbI7Mc


###
POST http://localhost:3000/category
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImRmNzNjMjllLTFiNzQtNGMyYi05NjMxLWY0NzhiMDQ3ZjhlNiIsIm5hbWUiOiJKb2huIERvZSIsImVtYWlsIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3Njc2NzQ2NzAsImV4cCI6MTc2Nzc2MTA3MH0.fCcNtu3bMN3lGDCXih4vbp_XAIzlDd6wLAkQHicLTVE

{
    "name":"other"
}

###
GET http://localhost:3000/product
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImRmNzNjMjllLTFiNzQtNGMyYi05NjMxLWY0NzhiMDQ3ZjhlNiIsIm5hbWUiOiJKb2huIERvZSIsImVtYWlsIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3NjgwOTg5ODUsImV4cCI6MTc2ODE4NTM4NX0.q1iZYWvgjocmFgIr6eItxLYF0M4pl76ptKc-SpbI7Mc

###
POST http://localhost:3000/product
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImRmNzNjMjllLTFiNzQtNGMyYi05NjMxLWY0NzhiMDQ3ZjhlNiIsIm5hbWUiOiJKb2huIERvZSIsImVtYWlsIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3NjgwOTg5ODUsImV4cCI6MTc2ODE4NTM4NX0.q1iZYWvgjocmFgIr6eItxLYF0M4pl76ptKc-SpbI7Mc

{
    "name": "product6",
    "price": 3,
    "categoryId": "30c89523-3976-486c-9aaf-eb69feae9342"
}

###
GET http://localhost:3000/inventory/334ad117-1121-4361-b958-e4b2c2b76b4b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImE3ODYzMjZiLTc3NWQtNDdhNC1iOTYwLTliOTA2MjJkMzA0YiIsInN1YiI6IkpvaG4gRG9lIiwiZW1haWwiOiJqb2huLmRvZUBleGFtcGxlLmNvbSIsImlhdCI6MTc2NzU1Njk0NiwiZXhwIjoxNzY3NjQzMzQ2fQ.fsZTdlC2NHD0RWWh0PhJpKUe--233zjhpfAbcjPecrI
