###
GET http://localhost:3000/product
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImI5OTNmNmM2LWZkZTktNGUyYi1hZDEzLTc4ZTJiMWU3NDFiNiIsInN1YiI6ImpvaG5kb2UiLCJpYXQiOjE3NjczMjcxNjksImV4cCI6MTc2NzQxMzU2OX0.tQARCmppuRmGZOeGycC5UxaGuWE724P-LWC1Ua0S7w8


###
POST http://localhost:3000/product
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImI5OTNmNmM2LWZkZTktNGUyYi1hZDEzLTc4ZTJiMWU3NDFiNiIsInN1YiI6ImpvaG5kb2UiLCJpYXQiOjE3NjczMjcxNjksImV4cCI6MTc2NzQxMzU2OX0.tQARCmppuRmGZOeGycC5UxaGuWE724P-LWC1Ua0S7w8

{
    "name": "product1",
    "price": 3,
    "categoryId": "category1"
}
