

###
GET http://localhost:3000/category
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImE3ODYzMjZiLTc3NWQtNDdhNC1iOTYwLTliOTA2MjJkMzA0YiIsInN1YiI6IkpvaG4gRG9lIiwiZW1haWwiOiJqb2huLmRvZUBleGFtcGxlLmNvbSIsImlhdCI6MTc2NzU1Njk0NiwiZXhwIjoxNzY3NjQzMzQ2fQ.fsZTdlC2NHD0RWWh0PhJpKUe--233zjhpfAbcjPecrI


###
POST http://localhost:3000/category
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImE3ODYzMjZiLTc3NWQtNDdhNC1iOTYwLTliOTA2MjJkMzA0YiIsInN1YiI6IkpvaG4gRG9lIiwiZW1haWwiOiJqb2huLmRvZUBleGFtcGxlLmNvbSIsImlhdCI6MTc2NzU1Njk0NiwiZXhwIjoxNzY3NjQzMzQ2fQ.fsZTdlC2NHD0RWWh0PhJpKUe--233zjhpfAbcjPecrI

{
    "name":"other"
}

###
GET http://localhost:3000/product
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImE3ODYzMjZiLTc3NWQtNDdhNC1iOTYwLTliOTA2MjJkMzA0YiIsInN1YiI6IkpvaG4gRG9lIiwiZW1haWwiOiJqb2huLmRvZUBleGFtcGxlLmNvbSIsImlhdCI6MTc2NzU1Njk0NiwiZXhwIjoxNzY3NjQzMzQ2fQ.fsZTdlC2NHD0RWWh0PhJpKUe--233zjhpfAbcjPecrI

###
POST http://localhost:3000/product
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImE3ODYzMjZiLTc3NWQtNDdhNC1iOTYwLTliOTA2MjJkMzA0YiIsInN1YiI6IkpvaG4gRG9lIiwiZW1haWwiOiJqb2huLmRvZUBleGFtcGxlLmNvbSIsImlhdCI6MTc2NzU1Njk0NiwiZXhwIjoxNzY3NjQzMzQ2fQ.fsZTdlC2NHD0RWWh0PhJpKUe--233zjhpfAbcjPecrI

{
    "name": "product3",
    "price": 3,
    "categoryId": "7056ebb9-9da9-4279-bdf2-3ef864cfc4e2"
}

###
GET http://localhost:3000/inventory/334ad117-1121-4361-b958-e4b2c2b76b4b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImE3ODYzMjZiLTc3NWQtNDdhNC1iOTYwLTliOTA2MjJkMzA0YiIsInN1YiI6IkpvaG4gRG9lIiwiZW1haWwiOiJqb2huLmRvZUBleGFtcGxlLmNvbSIsImlhdCI6MTc2NzU1Njk0NiwiZXhwIjoxNzY3NjQzMzQ2fQ.fsZTdlC2NHD0RWWh0PhJpKUe--233zjhpfAbcjPecrI
