###
POST http://localhost:3000/test
Content-Type: application/json

{
  "orderId": "123456"
}

###
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "John Doe",
  "password": "securepassword",
  "email": "john.doe@example.com",
  "userName": "johndoe"
}

###
POST http://localhost:3000/ccard
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImRmNzNjMjllLTFiNzQtNGMyYi05NjMxLWY0NzhiMDQ3ZjhlNiIsIm5hbWUiOiJKb2huIERvZSIsImVtYWlsIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3NjgwOTg5ODUsImV4cCI6MTc2ODE4NTM4NX0.q1iZYWvgjocmFgIr6eItxLYF0M4pl76ptKc-SpbI7Mc

{
  "cardNumber": "4111111111111111",
  "exp": "12/25",
  "cvv": "123",
  "cardHolderName": "John Doe",
  "userId": "df73c29e-1b74-4c2b-9631-f478b047f8e6"
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "password": "securepassword",
  "email": "john.doe@example.com"
}

###
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImRmNzNjMjllLTFiNzQtNGMyYi05NjMxLWY0NzhiMDQ3ZjhlNiIsIm5hbWUiOiJKb2huIERvZSIsImVtYWlsIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3NjgwOTg4NDksImV4cCI6MTc2ODE4NTI0OX0.BnSGvaYPDfCU0w1cagmbL7tx1KowkTCZxR4JVx6y7oY

###
GET http://localhost:3000/users/johndoe2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJlZDE0MDUxLTBjY2EtNDc1MC1iOWVkLTk0Zjg2ODMwODQzZiIsInN1YiI6ImpvaG5kb2UxIiwiaWF0IjoxNzY2Mjg4MzI1LCJleHAiOjE3NjYzNzQ3MjV9.zigrdcYtYp_--5Qj66cMinRVCqKcJ3Q92bH3RVTQ44g

###
PATCH http://localhost:3000/users/johndoe
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEyZWYwMmNlLTIwZjctNDAxZS04ZGMxLWMwNjYyMWQ5MWExZCIsInN1YiI6ImpvaG5kb2UxIiwiaWF0IjoxNzY1OTQ2ODgxLCJleHAiOjE3NjYwMzMyODF9.4iuMSvOs3tg5wUInSBQo9hDXvvS9DMeZAlF94A-1AsY

{
  "name": "John Doe",
  "userName": "johndoe",
  "password": "newsecurepassword"
}

###
DELETE http://localhost:3001/users/johndoe
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjViZDk2ZDUxLTI3NjgtNDAxNy1iYjA5LTFkOGNiOTcxM2E2YiIsInN1YiI6ImpvaG5kb2UiLCJpYXQiOjE3NjU5NDcxNzYsImV4cCI6MTc2NjAzMzU3Nn0.9epSKZFBzatBFVDsaBOF33FtOHwVT93M2Vgdr9RzGVg
