###
POST http://localhost:3004/payment
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVkYTU5MWVlLWExMTItNDY0OC05NWU0LWFhNWVjMjBlODU4MyIsIm5hbWUiOiJKb2huIERvZSIsImVtYWlsIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3Njk1NzQ1NzQsImV4cCI6MTc2OTY2MDk3NH0.3S3HPyoUqqgtB0GWMpBxcr9mCNZRvv1HAiIpXJbv0l8

{

}

###

GET http://localhost:3004/payment
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVkYTU5MWVlLWExMTItNDY0OC05NWU0LWFhNWVjMjBlODU4MyIsIm5hbWUiOiJKb2huIERvZSIsImVtYWlsIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3Njk1NzQ1NzQsImV4cCI6MTc2OTY2MDk3NH0.3S3HPyoUqqgtB0GWMpBxcr9mCNZRvv1HAiIpXJbv0l8
