###
GET http://localhost:3002

###
POST http://localhost:3002/order
Content-Type: application/json

{
    "userId": "sam",
    "orderItems": [{
        "productId": "abc",
        "quantity": 2,
        "price": 3.5
    },{
        "productId": "abcd",
        "quantity": 3,
        "price": 1.5
    }]

}