###
POST http://localhost:3001/users
Content-Type: application/json

{
  "name": "John Doe",
  "password": "securepassword",
  "email": "john.doe+1@example.com",
  "userName": "johndoe1"
}

###
POST http://localhost:3001/auth/login
Content-Type: application/json

{
  "password": "newsecurepassword",
  "userName": "johndoe"
}

###
GET http://localhost:3001/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEyZWYwMmNlLTIwZjctNDAxZS04ZGMxLWMwNjYyMWQ5MWExZCIsInN1YiI6ImpvaG5kb2UxIiwiaWF0IjoxNzY1OTQ2ODgxLCJleHAiOjE3NjYwMzMyODF9.4iuMSvOs3tg5wUInSBQo9hDXvvS9DMeZAlF94A-1AsY

###
GET http://localhost:3001/users/johndoe
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEyZWYwMmNlLTIwZjctNDAxZS04ZGMxLWMwNjYyMWQ5MWExZCIsInN1YiI6ImpvaG5kb2UxIiwiaWF0IjoxNzY1OTQ2ODgxLCJleHAiOjE3NjYwMzMyODF9.4iuMSvOs3tg5wUInSBQo9hDXvvS9DMeZAlF94A-1AsY

###
PATCH http://localhost:3001/users/johndoe
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEyZWYwMmNlLTIwZjctNDAxZS04ZGMxLWMwNjYyMWQ5MWExZCIsInN1YiI6ImpvaG5kb2UxIiwiaWF0IjoxNzY1OTQ2ODgxLCJleHAiOjE3NjYwMzMyODF9.4iuMSvOs3tg5wUInSBQo9hDXvvS9DMeZAlF94A-1AsY

{
  "name": "John Doe",
  "userName": "johndoe",
  "password": "newsecurepassword"
}

###
DELETE http://localhost:3001/users/johndoe
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjViZDk2ZDUxLTI3NjgtNDAxNy1iYjA5LTFkOGNiOTcxM2E2YiIsInN1YiI6ImpvaG5kb2UiLCJpYXQiOjE3NjU5NDcxNzYsImV4cCI6MTc2NjAzMzU3Nn0.9epSKZFBzatBFVDsaBOF33FtOHwVT93M2Vgdr9RzGVg
