export const PERMISSION_KEYS = {
  USER: "user",
  USER_ROLE: "user-role",
  TENANT: "tenant",
  ROLE: "role",
  ROLE_PERMISSION: "role-permission",
} as const;

export const PERMISSION_SCOPES = {
  CREATE: "create",
  UPDATE: "update",
  READ: "read",
  DELETE: "delete",
} as const;

export const PERMISSION_SCOPE_BY_KEY = {
  [PERMISSION_KEYS.USER]: {
    CREATE: PERMISSION_SCOPES.CREATE,
    READ: PERMISSION_SCOPES.READ,
    UPDATE: PERMISSION_SCOPES.UPDATE,
  },
  [PERMISSION_KEYS.USER_ROLE]: {
    CREATE: PERMISSION_SCOPES.CREATE,
    READ: PERMISSION_SCOPES.READ,
  },
  [PERMISSION_KEYS.TENANT]: {
    CREATE: PERMISSION_SCOPES.CREATE,
    READ: PERMISSION_SCOPES.READ,
    UPDATE: PERMISSION_SCOPES.UPDATE,
  },
  [PERMISSION_KEYS.ROLE]: {
    CREATE: PERMISSION_SCOPES.CREATE,
    READ: PERMISSION_SCOPES.READ,
    UPDATE: PERMISSION_SCOPES.UPDATE,
  },
  [PERMISSION_KEYS.ROLE_PERMISSION]: {
    CREATE: PERMISSION_SCOPES.CREATE,
    READ: PERMISSION_SCOPES.READ,
    UPDATE: PERMISSION_SCOPES.UPDATE,
    DELETE: PERMISSION_SCOPES.DELETE,
  },
} as const;
